version: '3'

services:
  django:
    build:
      context: ./containers
      dockerfile: Dockerfile.prod
    container_name: django

    # 外部公開はNginx経由にするので削除
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"  # Nginx から見える内部ポート

    tty: true

    working_dir: /root/workspace
    volumes:
      - ${SRC_PATH}:/root/workspace
      - static_volume:/root/workspace/staticfiles   # ← STATIC_ROOT と同じ場所を共有
      - media_volume:/root/workspace/media          # ←（ローカルMEDIAを暫定で配るなら）
    env_file:
      - .env
    # 例：エントリポイントをここで指定しているなら
    # command: bash entrypoint.prod.sh

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/conf.d/django.conf:/etc/nginx/conf.d/django.conf:ro
      - static_volume:/app/staticfiles:ro           # Nginx から見えるパス
      - media_volume:/app/media:ro                  # （必要なら）

volumes:
  static_volume:
  media_volume: