services:
  django:
    build:
      context: ./containers
      dockerfile: Dockerfile.prod
    container_name: django

    expose:
      - "8000"  # Nginx から見える内部ポート

    tty: true

    working_dir: /root/workspace
    volumes:
      - ${SRC_PATH}:/root/workspace
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: closet_search.settings.prod

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

volumes: {}