# Generated by Django 4.1 on 2025-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemphoto",
            name="delete_flag",
            field=models.BooleanField(default=False),
        ),
    ]
